@startuml Subscribe to Channels

actor Application_1 as app1
participant Server_1 as s1
participant Server_2 as s2
actor Application_2 as app2


== Setup ==

app2 -> s2 ++: createChannel(channelName, DLC)
s2 -> s2 : Copy Channel Name and\nDLC to txChannels Array
return

app1 -> s1 ++: subscribeToChannel(channelName, Callback)
s1 -> s1 : Copy Channel Name and\nCB to pendingChannels Array
return


== Loop ==
...Servers succesfully synchronized...

s1 ->> s2: SCRB Command:\nSends Channel Name

alt Valid Channel
    |||
    s2 ->> s1: SCRB_RSP Command:\nSends Channel Number,\nChannel DLC and\nChannel Name
    |||
else Invalid/Not Found Channel
    |||
    s2 ->> s1: SCRB_RSP Command:\nSends Channel Number = 0,\nChannel DLC = 0 and\nChannel Name
    |||
end

@enduml