@startuml

title Layers

package Application
package Service
package HAL

Application ..> Service: <<access>>
Application ..> HAL: <<access>>

Service ..> HAL: <<access>>

package Target
package Simulation

HAL <|.. Target: <<realize>>
HAL <|.. Simulation: <<realize>>

@enduml