@startuml Deployment

title Deployment

node "PC" as pc

node "Pololu Zumo32U4" as zumo32u4 {

    node "Main Board" as mainBoard {

        node "MCU\nAVR32U4" as mcu {
            component "Radon Ulzer" as software <<software>>
        }

        component "Buttons" as buttons <<hardware>>
        component "Buzzer" as buzzer <<hardware>>
        component "Motors" as motors <<hardware>>
        component "Encoders" as encoders <<hardware>>
        component "LEDs" as leds <<hardware>>
        component "ProximitySensors" as proximitySensors <<hardware>>
        component "Accelerometer" as accelerometer <<hardware>>
        component "Gyroscope" as gyroscope <<hardware>>

        software -u- buttons
        software -u- leds
        software -u- proximitySensors
        software -u- accelerometer
        software -- buzzer
        software -- motors
        software -- encoders
        software -- gyroscope
    }

    node "Front Sensor Array" {
        component "Line sensors" as lineSensors <<hardware>>
    }

    node "LCD" {
        component "LCD" as lcd <<hardware>>
    }

    software - lcd
    software -- lineSensors    
}

interface "USB" as usb

zumo32u4 -l- usb
usb )-l- pc

note top of zumo32u4
    Only the used actors and sensors are shown.
    The LCD and front sensor array are connected to the main board
    and can be plugged in or out.
end note

@enduml