; PlatformIO Project Configuration File
;
; Used for user specific configurations.

; *****************************************************************************
; Common configurations, which is independed of the environment.
; *****************************************************************************
[common]
build_flags =
    -D TEAM_NAME_LINE_1="\"Radon\""
    -D TEAM_NAME_LINE_2="\"Ulzer\""
    -D CONFIG_USE_OLED_DISPLAY=0

; *****************************************************************************
; Target environment for the actual robot.
;
; Choose Zumo32U4 for the original Zumo robot with ATmega32U4 by changing the line below to
; extends = hal:Zumo32U4 and the extra_scripts line to {hal:Zumo32U4.extra_scripts}
;
; Choose ZumoRP2040 for the new Zumo robot with RP2040 by changing the line below to
; extends = hal:ZumoRP2040 and the extra_scripts line to {hal:ZumoRP2040.extra_scripts}
; *****************************************************************************
[hal:Target]
extends = hal:Zumo32U4
extra_scripts =
    {hal:Zumo32U4.extra_scripts}
    ./scripts/add_target_tasks.py

; *****************************************************************************
; Target environment for Zumo32U4.
; *****************************************************************************
[hal:Zumo32U4]
; The monitor port shows the debug output and the test output.
; If you connect the robot to your pc, this is the port you will see.
monitor_port = com11

; The upload port is spawned by the bootmonitor and used to update the program on the target.
; If you connect the robot to your pc, press twice reset button to jump to the bootloader,
; this is the port you will see.
upload_port = com5

; The test port is spawned by the bootmonitor and used to update the test on the target.
; If you connect the robot to your pc, press twice reset button to jump to the bootloader,
; this is the port you will see.
test_port = com9

; *****************************************************************************
; PC target environment for Webots simulation.
;
; It is assumed that the environment variable WEBOTS_HOME is set to the
; Webots directory, e.g. WEBOTS_HOME=C:\Users\<user>\AppData\Local\Programs\Webots
; *****************************************************************************
[hal:Sim]
custom_webots_ip_address = 127.0.0.1 ; IP address of the Webots simulation, which is used for TCP communication
custom_webots_protocol = ipc ; [ipc|tcp] - ipc is faster but only works on the same machine, tcp works also over network
custom_webots_robot_name = Zumo
custom_webots_supervisor_serial_rx_channel = 1
custom_webots_supervisor_serial_tx_channel = 2
custom_webots_robot_serial_rx_channel = 3
custom_webots_robot_serial_tx_channel = 4
custom_settings_path = ./settings/settings.json
