@startuml

title System States

state StartupState
state LineSensorsCalibrationState
state ErrorState
state DrivingState
state ReadyState
state ReleaseTrackState

[*] --> StartupState: Power up
StartupState --> LineSensorsCalibrationState: [Pushbutton A triggered]
LineSensorsCalibrationState --> ReadyState: [Calibration finished]
LineSensorsCalibrationState --> ErrorState: [Calibration failed]
ReadyState --> ReleaseTrackState: [Pushbutton A triggered]
ReleaseTrackState --> DrivingState: [After 5s]
ReleaseTrackState --> ReleaseTrackState: [Pushbutton A triggered]
DrivingState --> ReadyState: [End line detected] or\n[Track lost] or\n[End line not found after 5 min.]
ErrorState --> LineSensorsCalibrationState: [Pushbutton A triggered]

note right of StartupState
    Initialize the system and wait till
    the operator is ready for calibration.
end note

note right of LineSensorsCalibrationState
    Calibrates the system on the playfield.
end note

note left of ErrorState
    Shows error to the operator.
end note

note right of ReadyState
    Waits for the operator to start the competition.
end note

note left of ReleaseTrackState
    The operator can select the parameter set
    and releases the track after a certain time.
end note

note right of DrivingState
    The system drives autonomous on track, detects
    start and end line. Additional it handels a
    detected gap as well.
end note

@enduml