@startuml SensorFusionSystemStates

title System States

state StartupState: /entry Initialize HAL.
state StartupState: /entry Try to load Max. Motor Speed from Settings.

state LineSensorsCalibrationState: /do Perform calibration.

state ErrorState: /do Wait for pushbutton A to be triggered.

state ReadyState: /do Wait for pushbutton A to be triggered.

state ReleaseTrackState: /entry Choose parameter set 0
state ReleaseTrackState: /entry Start release timer.
state ReleaseTrackState: /do If pushbutton A to be triggered, choose next parameter set.
state ReleaseTrackState: /do If pushbutton A to be triggered, restart release timer.
state ReleaseTrackState: /exit Stop release timer.

state DrivingState: /entry Start observation timer.
state DrivingState: /do Perform driving.
state DrivingState: /do Read out Odometry unit and IMU.
state DrivingState: /do Send Odometry values and IMU values via SerialMuxProt.
state DrivingState: /exit Stop observation timer.

[*] --> StartupState: Power up
StartupState --> LineSensorsCalibrationState: [Max. Motor Speed is defined]
StartupState --> ErrorState: [Max. Motor Speed is not defined]
LineSensorsCalibrationState --> ReadyState: [Calibration finished]
LineSensorsCalibrationState --> ErrorState: [Calibration failed]
ReadyState --> ReleaseTrackState: [Pushbutton A triggered]
ReleaseTrackState --> DrivingState: [Release timer timeout]
ReleaseTrackState --> ReleaseTrackState: [Pushbutton A triggered]
DrivingState --> ReadyState: [Track lost] or\n[Observation timer timeout]
ErrorState --> StartupState: [Pushbutton A triggered]

@enduml