@startuml

title Configuration

package "platformio.ini" {

    package "working environments" {
        component "env:<APPLICATION-NAME>Target" <<pio>> as pioEnvAppTarget
        component "env:<APPLICATION-NAME>Sim" <<pio>> as pioEnvAppSim
    }

    package "configuration environments" as cfgEnv {

        component "hal_app:<APPLICATION-NAME>Target" <<pio>> as pioHalAppTarget
        component "app:<APPLICATION-NAME>" <<pio>> as pioAppApp
        component "hal_app:<APPLICATION-NAME>Sim" <<pio>> as pioHalAppSim

        component "hal:Zumo" <<pio>> as pioHalTarget
        component "hal:Sim" <<pio>> as pioHalSim
    }
}

package "/lib" as libFolder {

    component "HALInterfaces" <<lib>> as halInterfacesLib

    component "APP<APPLICATION-NAME>" <<lib>> as appLib
    component "Service" <<lib>> as serviceLib

    component "HAL<APPLICATION-NAME>Target" <<lib>> as halAppTarget
    component "HAL<APPLICATION-NAME>Sim" <<lib>> as halAppSim

    component "HALTarget" <<lib>> as halTargetLib
    component "HALSim" <<lib>> as halSimLib

    component "Webots" <<lib>> as webotsLib
    component "ArduinoNative" <<lib>> as arduinoNativeLib

    note bottom of halAppTarget
        Application specific target HAL
        instantiation via Board class.
        May use less peripherals, than
        available.
    end note

    note bottom of halAppSim
        Application specific simulation HAL
        instantiation via Board class.
        May use less peripherals, than
        available.
    end note

    note bottom of halTargetLib
        Contains the target HAL
        peripheral classes.
    end note

    note bottom of halSimLib
        Contains the simulation HAL
        peripheral classes.
    end note

    note bottom of halInterfacesLib
        Defines the interfaces
        of the HAL peripherals.
    end note

    note bottom of appLib
        Application specific functionality.
    end note

    note bottom of serviceLib
        General services, used by
        the applications.
    end note

    note bottom of webotsLib
        Webots simulation glue code.
    end note

    note bottom of arduinoNativeLib
        Some stubbed Arduino interfaces
        for simulation.
    end note
}

pioEnvAppTarget ...> pioAppApp: <<extends>>
pioEnvAppTarget ...> pioHalAppTarget: <<extends>>

pioHalAppTarget ..> pioHalTarget: <<extends>>
pioHalAppTarget ...> halAppTarget: <<depends>>

pioHalTarget ..> halTargetLib: <<depends>>
pioHalTarget ..> halInterfacesLib: <<depends>>


pioEnvAppSim ..> pioAppApp: <<extends>>
pioEnvAppSim ..> pioHalAppSim: <<extends>>

pioHalAppSim ..> pioHalSim: <<extends>>
pioHalAppSim ...> halAppSim: <<depends>>

pioHalSim ..> halSimLib: <<depends>>
pioHalSim ..> webotsLib: <<depends>>
pioHalSim ..> halInterfacesLib: <<depends>>
pioHalSim ..> arduinoNativeLib: <<depends>>


pioAppApp ...> appLib: <<depends>>
pioAppApp ...> serviceLib: <<depends>>

@enduml