@startuml RemoteControl System States

title System States

state StartupState
state MotorSpeedCalibrationState
state ErrorState
state RemoteCtrlState
state ReadyState

[*] --> StartupState: Power up
StartupState --> MotorSpeedCalibrationState: [Pushbutton A triggered]
MotorSpeedCalibrationState --> ReadyState: [Calibration finished]
MotorSpeedCalibrationState --> ErrorState: [Calibration failed]
ReadyState --> RemoteCtrlState: [Operator connects]
RemoteCtrlState --> ReadyState: [Connection lost]
ErrorState --> MotorSpeedCalibrationState: [Pushbutton A triggered]
ReadyState --> ErrorState: [Connection Timeout]
RemoteCtrlState --> ErrorState: [Fatal error]

note right of StartupState
    Initialize the system and wait till
    the operator is ready for calibration.
end note

note right of MotorSpeedCalibrationState
    Measures the max. left/right encoder steps / s with
    100% motor speed. Required for the motor speed PID.
end note

note left of ErrorState
    Shows error to the operator.
end note

note right of ReadyState
    Waits for the operator to connect using the Remote Control.
end note

note right of RemoteCtrlState
    The system drives according to the commands sent by the operator.
    Additionally, it prevents crashes using the proximity sensors.
end note

@enduml