@startuml RemoteControl System States

title System States

state StartupState
state LineSensorsCalibrationState
state ErrorState
state DrivingState

[*] --> StartupState: Power up
StartupState --> DrivingState

DrivingState --> LineSensorsCalibrationState: [on remote request]

LineSensorsCalibrationState --> DrivingState: [Calibration finished]
LineSensorsCalibrationState --> ErrorState: [Calibration failed]

ErrorState --> DrivingState: [Pushbutton A triggered]

note right of StartupState
    Initialize the system and show application name.
end note

note right of LineSensorsCalibrationState
    Calibrates the line sensors on the playfield by
    measuring the the darkness and brightness values.
end note

note left of ErrorState
    Shows error to the operator.
end note

note right of DrivingState
    The system drives according to the commands sent by the operator.
end note

@enduml