@startuml

title System States

state StartupState
state MotorSpeedCalibrationState
state LineSensorsCalibrationState
state ErrorState
state DrivingState
state ReadyState
state ReleaseTrackState

[*] --> StartupState: Power up
StartupState --> MotorSpeedCalibrationState: [Pushbutton A triggered]
StartupState --> LineSensorsCalibrationState: [Pushbutton B triggered] and\n[Max. motor speed calib. is available in settings]
MotorSpeedCalibrationState --> LineSensorsCalibrationState: [Calibration finished]
LineSensorsCalibrationState --> ReadyState: [Calibration finished]
LineSensorsCalibrationState --> ErrorState: [Calibration failed]
ReadyState --> ReleaseTrackState: [Pushbutton A triggered]
ReleaseTrackState --> DrivingState: [After 5s]
ReleaseTrackState --> ReleaseTrackState: [Pushbutton A triggered]
DrivingState --> ReadyState: [End line detected] or\n[Track lost] or\n[End line not found after 5 min.]
ErrorState --> StartupState: [Pushbutton A triggered]

note right of StartupState
    Initialize the system and wait till
    the operator is ready for calibration.
end note

note right of MotorSpeedCalibrationState
    Measures the max. left/right encoder steps / s with
    100% motor speed. Required for the motor speed PID.

    Stores the calibration value in the settings persistent.
end note

note left of LineSensorsCalibrationState
    Calibrates the line sensors on the playfield by
    measuring the the darkness and brightness values.
end note

note bottom of ErrorState
    Shows error to the operator.
end note

note left of ReadyState
    Waits for the operator to start the competition.
end note

note left of ReleaseTrackState
    The operator can select the parameter set
    and releases the track after a certain time.
end note

note right of DrivingState
    The system drives autonomous on track, detects
    start and end line. Additional it handels a
    detected gap as well.
end note

@enduml