@startuml

title Layers

package Application
package Service
package HAL

Application ..> Service: <<access>>
Application ...> HAL: <<access>>

Service ..> HAL: <<access>>

package "HAL" as halDetail {
    package ZumoHALInterfaces
    package ZumoHALATmega32u4
    package ZumoHALWebots
    package HALTest

    ZumoHALInterfaces <|.. ZumoHALATmega32u4: <<realize>>
    ZumoHALInterfaces <|.. ZumoHALWebots: <<realize>>
    ZumoHALInterfaces <|.. HALTest: <<realize>>
}

HAL -[hidden]-- halDetail

note top of halDetail
    HAL white box view
end note

@enduml